# Dependabot configuration for automated dependency updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Go modules - Backend services
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "georg-nikola"
    labels:
      - "dependencies"
      - "go"
      - "automated"
    commit-message:
      prefix: "deps(go)"
      include: "scope"
    groups:
      go-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # npm - Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "georg-nikola"
    labels:
      - "dependencies"
      - "javascript"
      - "frontend"
      - "automated"
    commit-message:
      prefix: "deps(npm)"
      include: "scope"
    groups:
      vue-ecosystem:
        patterns:
          - "vue*"
          - "@vue/*"
          - "vite*"
        update-types:
          - "minor"
          - "patch"
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  # pip - ML Service dependencies
  - package-ecosystem: "pip"
    directory: "/ml"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "georg-nikola"
    labels:
      - "dependencies"
      - "python"
      - "ml-service"
      - "automated"
    commit-message:
      prefix: "deps(python)"
      include: "scope"
    groups:
      python-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Docker - All Dockerfiles
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "georg-nikola"
    labels:
      - "dependencies"
      - "docker"
      - "automated"
    commit-message:
      prefix: "deps(docker)"

  # Docker - ML Service Dockerfile
  - package-ecosystem: "docker"
    directory: "/ml"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "georg-nikola"
    labels:
      - "dependencies"
      - "docker"
      - "ml-service"
      - "automated"
    commit-message:
      prefix: "deps(docker)"

  # GitHub Actions - Workflow dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "georg-nikola"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci-cd"
      - "automated"
    commit-message:
      prefix: "deps(actions)"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
