---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-service
  namespace: sentinel-mesh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-service
  template:
    metadata:
      labels:
        app: ml-service
    spec:
      containers:
      - name: ml-service
        image: sentinel-mesh/ml-service:staging
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: ml-service
  namespace: sentinel-mesh
spec:
  selector:
    app: ml-service
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
