global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'sentinel-mesh-dev'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'collector'
    static_configs:
      - targets: ['collector:8080']
    metrics_path: '/metrics'

  - job_name: 'processor'
    static_configs:
      - targets: ['processor:8080']
    metrics_path: '/metrics'

  - job_name: 'analyzer'
    static_configs:
      - targets: ['analyzer:8080']
    metrics_path: '/metrics'

  - job_name: 'alerting'
    static_configs:
      - targets: ['alerting:8080']
    metrics_path: '/metrics'

  - job_name: 'api'
    static_configs:
      - targets: ['api:8080']
    metrics_path: '/metrics'

  - job_name: 'ml-service'
    static_configs:
      - targets: ['ml-service:8000']
    metrics_path: '/metrics'
