name: Enable Auto-Merge on Approval

on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  pull-requests: write

jobs:
  enable-auto-merge:
    name: Enable Auto-Merge
    runs-on: ubuntu-latest
    # Only run when PR is approved
    if: github.event.review.state == 'approved'

    steps:
      - name: Enable auto-merge
        run: |
          gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on PR
        run: |
          gh pr comment "$PR_URL" --body "✅ Auto-merge enabled. This PR will merge automatically once all status checks pass."
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
